import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MostraServiceService {

  mostre: any = [
    {id: 1 ,nomeMostra:"Il rinascimento - I capolavori di Buonarroti", nomeArtista: "Michelangelo Buonarroti", img: "../assets/img/buonarroti.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Michelangelo, artista poliedrico e indiscusso protagonista del Rinascimento italiano, viene celebrato in questa mostra che esplora la sua vasta produzione artistica. Scopriremo il suo genio creativo che si è espresso in maniera magistrale nella scultura, nella pittura e nell'architettura.", dataInizio: new Date().getTime() + (2 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (3 * 30 * 24 * 60 * 60 * 1000)},
    {id: 2 ,nomeMostra:"Caravaggio - Il Maestro dell'Ombra e della Luce", nomeArtista: "Caravaggio", img: "../assets/img/caravaggio.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante alla scoperta di uno dei più grandi artisti del Seicento italiano: Michelangelo Merisi da Caravaggio. Pittore rivoluzionario, capace di sconvolgere le regole artistiche del suo tempo con il suo uso magistrale della luce e dell'ombra, Caravaggio ha lasciato un'eredità indelebile nella storia dell'arte.", dataInizio: new Date().getTime() + (5 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (6 * 30 * 24 * 60 * 60 * 1000)},
    {id: 3 ,nomeMostra:"Gustave Doré - Maestro dell'Illustrazione e del Fantastico", nomeArtista: "Gustave Doré",img: "../assets/img/doré.jpg" , imgLogo:"../assets/img/logoArte.png", descrizione:"Un'immersione affascinante nell'universo visionario di Gustave Doré, uno dei più grandi illustratori di tutti i tempi. Attraverso le sue opere, saremo trasportati in mondi fantastici, tra atmosfere fiabesche,", dataInizio: new Date().getTime() + (9 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (11 * 30 * 24 * 60 * 60 * 1000)},
    {id: 4 ,nomeMostra:"Francisco Goya - I Capricci della Mente Umana", nomeArtista: "Francisco Goya",img: "../assets/img/goya.jpg" , imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante e disturbante nell'universo oscuro e visionario di Francisco Goya, uno dei più grandi artisti del Romanticismo spagnolo. Attraverso le sue opere, spesso grottesche e satiriche, esploreremo i lati più reconditi dell'animo umano, tra follia, violenza, superstizione e critica sociale.", dataInizio: new Date().getTime() + (10 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (11 * 30 * 24 * 60 * 60 * 1000)},
    {id: 5 ,nomeMostra:"Umberto Boccioni - Dinamismo e Luce Futurista", nomeArtista: "Umberto Boccioni", img: "../assets/img/boccioni.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio immersivo nell'universo artistico di Umberto Boccioni, pioniere del Futurismo italiano e maestro dell'avanguardia del XX secolo. Attraverso le sue opere scultoree e pittoriche, esploreremo il dinamismo delle macchine, la velocità del movimento e la luce come elemento chiave per la rappresentazione della realtà.", dataInizio: new Date().getTime() + (1 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (3 * 30 * 24 * 60 * 60 * 1000)},
    {id: 6 ,nomeMostra:"Edvard Munch - Esplorando l'Angoscia dell'Esistenza", nomeArtista: "Edvard Munch", img: "../assets/img/munch.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante e profondo nell'universo artistico di Edvard Munch, uno dei più grandi esponenti dell'Espressionismo norvegese. Attraverso le sue opere, spesso cariche di simbolismo e pathos, esploreremo le tematiche fondamentali della sua poetica: l'angoscia esistenziale, la solitudine, l'amore, la morte e il rapporto con la natura.", dataInizio: new Date().getTime() + (8 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (10 * 30 * 24 * 60 * 60 * 1000)},
    {id: 7 ,nomeMostra:"Claude Monet - Maestro dell'Impressionismo", nomeArtista: "Claude Monet",img: "../assets/img/monet.jpg" , imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante alla scoperta di uno dei più grandi artisti del XIX secolo, Claude Monet. Pittore francese, pioniere dell'Impressionismo, Monet ha rivoluzionato la rappresentazione della realtà attraverso la sua attenzione alla luce, al colore e alla resa immediata della percezione visiva.", dataInizio: new Date().getTime() + (5 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (6 * 30 * 24 * 60 * 60 * 1000)}

  ]

  mostra1: any = [
    {id: 1 ,nomeMostra:"Il rinascimento - I capolavori di Buonarroti", nomeArtista: "Michelangelo Buonarroti", img: "../assets/img/buonarroti.jpg", imgO1:"../assets/img/buonarroti1.jpg" , imgO2:"../assets/img/buonarroti2.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Michelangelo, artista poliedrico e indiscusso protagonista del Rinascimento italiano, viene celebrato in questa mostra che esplora la sua vasta produzione artistica. Scopriremo il suo genio creativo che si è espresso in maniera magistrale nella scultura, nella pittura e nell'architettura.", dataInizio: new Date().getTime() + (2 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (3 * 30 * 24 * 60 * 60 * 1000)}
  ]

  mostra2: any = [
    {id: 2 ,nomeMostra:"Caravaggio - Il Maestro dell'Ombra e della Luce", nomeArtista: "Caravaggio", img: "../assets/img/caravaggio.jpg", imgO1:"../assets/img/caravaggio1.jpg" , imgO2:"../assets/img/caravaggio2.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante alla scoperta di uno dei più grandi artisti del Seicento italiano: Michelangelo Merisi da Caravaggio. Pittore rivoluzionario, capace di sconvolgere le regole artistiche del suo tempo con il suo uso magistrale della luce e dell'ombra, Caravaggio ha lasciato un'eredità indelebile nella storia dell'arte.", dataInizio: new Date().getTime() + (5 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (6 * 30 * 24 * 60 * 60 * 1000)}
  ]

  mostra3: any = [
    {id: 3 ,nomeMostra:"Gustave Doré - Maestro dell'Illustrazione e del Fantastico", nomeArtista: "Gustave Doré",img: "../assets/img/doré.jpg", imgO1:"../assets/img/doré1.jpg" , imgO2:"../assets/img/doré2.jpg" , imgLogo:"../assets/img/logoArte.png", descrizione:"Un'immersione affascinante nell'universo visionario di Gustave Doré, uno dei più grandi illustratori di tutti i tempi. Attraverso le sue opere, saremo trasportati in mondi fantastici, tra atmosfere fiabesche,", dataInizio: new Date().getTime() + (9 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (11 * 30 * 24 * 60 * 60 * 1000)}
  ]

  mostra4: any = [
    {id: 4 ,nomeMostra:"Francisco Goya - I Capricci della Mente Umana", nomeArtista: "Francisco Goya",img: "../assets/img/goya.jpg", imgO1:"../assets/img/goya1.jpg" , imgO2:"../assets/img/goya2.jpg" , imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante e disturbante nell'universo oscuro e visionario di Francisco Goya, uno dei più grandi artisti del Romanticismo spagnolo. Attraverso le sue opere, spesso grottesche e satiriche, esploreremo i lati più reconditi dell'animo umano, tra follia, violenza, superstizione e critica sociale.", dataInizio: new Date().getTime() + (10 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (11 * 30 * 24 * 60 * 60 * 1000)},
  ]

  mostra5: any = [
    {id: 5 ,nomeMostra:"Umberto Boccioni - Dinamismo e Luce Futurista", nomeArtista: "Umberto Boccioni", img: "../assets/img/boccioni.jpg", imgO1:"../assets/img/boccioni1.jpg" , imgO2:"../assets/img/boccioni2.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio immersivo nell'universo artistico di Umberto Boccioni, pioniere del Futurismo italiano e maestro dell'avanguardia del XX secolo. Attraverso le sue opere scultoree e pittoriche, esploreremo il dinamismo delle macchine, la velocità del movimento e la luce come elemento chiave per la rappresentazione della realtà.", dataInizio: new Date().getTime() + (1 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (3 * 30 * 24 * 60 * 60 * 1000)}
  ]

  mostra6: any = [
    {id: 6 ,nomeMostra:"Edvard Munch - Esplorando l'Angoscia dell'Esistenza", nomeArtista: "Edvard Munch", img: "../assets/img/munch.jpg", imgO1:"../assets/img/munch1.jpg" , imgO2:"../assets/img/munch2.jpg" ,imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante e profondo nell'universo artistico di Edvard Munch, uno dei più grandi esponenti dell'Espressionismo norvegese. Attraverso le sue opere, spesso cariche di simbolismo e pathos, esploreremo le tematiche fondamentali della sua poetica: l'angoscia esistenziale, la solitudine, l'amore, la morte e il rapporto con la natura.", dataInizio: new Date().getTime() + (8 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (10 * 30 * 24 * 60 * 60 * 1000)}
  ]

  mostra7: any = [
    {id: 7 ,nomeMostra:"Claude Monet - Maestro dell'Impressionismo", nomeArtista: "Claude Monet",img: "../assets/img/monet.jpg", imgO1:"../assets/img/monet1.jpg" , imgO2:"../assets/img/monet2.jpg" , imgLogo:"../assets/img/logoArte.png", descrizione:"Un viaggio affascinante alla scoperta di uno dei più grandi artisti del XIX secolo, Claude Monet. Pittore francese, pioniere dell'Impressionismo, Monet ha rivoluzionato la rappresentazione della realtà attraverso la sua attenzione alla luce, al colore e alla resa immediata della percezione visiva.", dataInizio: new Date().getTime() + (5 * 30 * 24 * 60 * 60 * 1000), dataFine: new Date().getTime() + (6 * 30 * 24 * 60 * 60 * 1000)}
  ]
}
